version: '3.3'

services:
    nginx:

        image: nginx:latest

        container_name: nginx

        ports:
            - "80:80"

        volumes:
            - ./Nginx/core:/etc/nginx/conf.d
            - ./Nginx/www:/var/www/


